/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cafe_Sales_Managment;

import java.awt.Menu;
import java.sql.*;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author ucwaz
 */
public class Login_UI extends javax.swing.JFrame {

    /**
     * Creates new form Login_UI
     */
    public Login_UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        SignUpbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Loginbtn1 = new javax.swing.JButton();
        cmbRole = new javax.swing.JComboBox<>();
        Showpass = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 70, -1));

        Username.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Username");
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 70, -1));
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 180, -1));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 180, -1));

        SignUpbtn.setText("Sign Up");
        SignUpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpbtnActionPerformed(evt);
            }
        });
        jPanel1.add(SignUpbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("____________");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 80, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("____________");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 80, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("or");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 50, -1));

        Loginbtn1.setText("Login");
        Loginbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Loginbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(Loginbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Role", "Staff", "Customer" }));
        jPanel1.add(cmbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 140, -1));

        Showpass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Showpass.setText("Show Password");
        Showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowpassActionPerformed(evt);
            }
        });
        jPanel1.add(Showpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\computer files\\Mona Waazeer\\cafeeee.jpg")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -540, 400, 940));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpbtnActionPerformed
        // TODO add your handling code here:
        SignUp_UI SUPUI = new SignUp_UI();
        SUPUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SignUpbtnActionPerformed

    private void Loginbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Loginbtn1ActionPerformed
        // TODO add your handling code here:
        DashboardUI dashboard = new DashboardUI();
        MenuUI menu = new MenuUI();

        String username = txtUsername.getText().trim();
        String password = String.valueOf(txtPassword.getPassword());
        String selectedRole = cmbRole.getSelectedItem().toString();

        if (username.equals("") || password.equals("") || selectedRole.equals("Select Role")) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields and select a role!");
            return;
        }

        try {
            Connection conClass = ConnectionClass.createConnection();
            String query = "SELECT * FROM login WHERE Username = ? AND Password = ? AND role = ?";
            PreparedStatement pst = conClass.prepareStatement(query);
            pst.setString(1, username);
            pst.setString(2, password);
            pst.setString(3, selectedRole.toLowerCase()); // assuming DB stores 'staff' or 'customer'

            ResultSet resultSet = pst.executeQuery();

            if (resultSet.next()) {
                JOptionPane.showMessageDialog(this, "Login Successful!");

                if (selectedRole.equalsIgnoreCase("staff")) {
                    dashboard.setVisible(true);
                } else if (selectedRole.equalsIgnoreCase("customer")) {
                    menu.setVisible(true);
                }

                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Invalid username, password, or role!");
            }

            resultSet.close();
            pst.close();
            conClass.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_Loginbtn1ActionPerformed

    private void ShowpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowpassActionPerformed
        // TODO add your handling code here:
        if (Showpass.isSelected())
        {
            txtPassword.setEchoChar((char)0);
        }
        else
        {
            txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_ShowpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Loginbtn1;
    private javax.swing.JCheckBox Showpass;
    private javax.swing.JButton SignUpbtn;
    private javax.swing.JLabel Username;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
